version: '3'
services:
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - .env.dev
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    env_file:
      - .env.dev
    volumes:
      - grafana:/var/lib/grafana

volumes:
  grafana:
  influxdb: